### ISSUE TITLE
Solapamiento de números romanos largos en los elementos de las listas.

### ISSUE THREAD

**Issue by aradnix** [aradnix/consti#1]
Hay que corregir la distancia en las listas que se generan con número romanos para que cuando haya un elemento con un numero grande, digamos XVIII no choque y se solape con el texto del elemento.

**Comment by ousia** [comment]
Esto lo tengo que ver. Perdona, pero lo dejo para mañana.

**Comment by aradnix** [comment]
Descuida no hay prisa y gracias por todo.

**Comment by ousia** [comment]
Al final me liberé de algo y mañana tendré que hacerlo de otro modo.

**Comment by ousia** [comment]
@aradnix, creo que ya está solucionado con 492781426b69e8da5c09c9e7b1955015588769d7.

**Comment by ousia** [comment]
Cierro porque está solucionado.
