### ISSUE TITLE
tipos e interlineado

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#10]
El interlineado en ConTeXt se establece para todo el documento con:

``` tex
\setupinterlinespace[line=2.8ex]
```

Es el valor por defecto, aunque dependiendo de la tipografía, puede ser un poco pequeño. Por ejemplo, para _TeX Gyre Pagella_, debería ser:

``` tex
\setupinterlinespace[line=2.8ex]
\setupbodyfont[pagella]
```

La unidad de medida es relativa a la tipografía usada, pero el interlineado no cambia en tipos muy grandes. Pero la distancia es relativa al tamaño del tipo de `\setupbodyfont` (por defecto: `12pt`).

Compara:

``` tex
{\tfd Constitución Política de la\\ República Mexicana}
```

con

``` tex
{\tfd\setupinterlinespace Constitución Política de la\\ República Mexicana\par}
```

Así usado, `\setupinterlinespace` provoca que recalcule el interlineado para el tamaño del tipo actual. Para que funcione, hay que introducir `\par` en el mismo grupo de llaves.

**Comment by aradnix** [comment]
Interesante, y sí ya había leído algo sobre ese uso particular de `\par`. Gracias
