### ISSUE TITLE
plantilla

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#11]
Como puedes ver, en mi publicación pasé `\showgrid` a primera línea. Así es más fácil activarlo o desactivarlo.

Pero sobre todo `grid=yes` en `\setuplayout` debe ser la opción por defecto. No es necesaria.

**Comment by aradnix** [comment]
Perfecto, lo muevo a la primer línea.

**Comment by ousia** [comment]
Y en la primera línea puedes añadir (yo lo tengo siempre):

``` tex
\showframe\showgrid
```

Así, lo activas y desactivas fácilmente.

**Comment by aradnix** [comment]
Muy bien, lo tomo en cuenta.

**Comment by ousia** [comment]
@aradnix, perdona pero aquí me colé yo.

`\showgrid` te muestra la plantilla del documento. `\setuplayout[grid=yes]` coloca todas las líneas en cada una de las plantillas del documento.

La diferencia entre activar y desactivar la línea comentada está en:

``` tex
\showgrid\showframe
\setuppapersize[A5]
%~ \setuplayout[grid=yes]
\starttext
\section{Donald E. Knuth}
\input knuth
\section{Hermann Zapf}
\input zapf
\stoptext
```

Con `\setuplayout[grid=yes]`:

![plantilla-1](https://cloud.githubusercontent.com/assets/203767/7334537/bf942c1c-eb96-11e4-8cfa-523d12472893.png)

Sin `\setuplayout[grid=yes]`:

![plantilla-1](https://cloud.githubusercontent.com/assets/203767/7334542/f20f8344-eb96-11e4-903e-b3396dcf29a5.png)

Por tanto, lo que te había dicho antes estaba equivocado. Reconozco que no creo que use nunca `\setuplayout[grid=yes]`. Pero el error era mío.
