### ISSUE TITLE
documentos interactivos

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#12]
Los documentos interactivos en ConText se consiguen añadiendo en el preámbulo:

``` tex
\setupinteraction[state=start, color=, style=, focus=standard]
\enabledirectives[references.border]
```

La línea importante es la primera. Como su propio nombre indica:

``` tex
\setupinteraction[state=start]
```

Es lo que activa la interactividad del documento.

En esa misma orden, hay las siguientes opciones:
- `style` por defecto es negrita. (Tal como está, se anula un estilo especial. Así sirve para que el mismo documento pueda ser interactivo y para impresión.)
- `color` por defecto verde o rojo, según el destino sea externo o interno a la misma página del enlace. (Anulo el valor, como en el caso anterior.)
- `focus` aconsejo poner valor `standard` para que no cambie el modo en que vemos la página tras pinchar en un enlace con destino dentro del documento.

La segunda línea añade recuadros en los enlaces del documento:

``` tex
\enabledirectives[references.border]
```

Tres consideraciones sobre los enlaces interactivos y sus recuadros:
- Sólo funcionan los recuadros de los enlaces, cuando hay enlaces interactivos. Esto es, la segunda línea necesita de la primera.
- Los destinos de los enlaces (especialmente en las notas) funcionan mal. Espero que se solucione en la próxima versión de la _ConTeXt Suite_ (lo que supone _TeX Live 2015_).
- El color del recuadro se puede cambiar sustituyendo `\enabledirectives[references.border=red]`.

Y creo que no me olvido nada.

**Comment by aradnix** [comment]
Pues muy claro e interesante, más simple que hyperrref en LaTeX.

**Comment by ousia** [comment]
Aquí se me olvidaron los marcadores (van en la segunda línea):

``` tex
    \setupinteraction[state=start]
    \setupinteractionscreen[option=bookmark]
    \placebookmarks[chapter,section][chapter]
    \starttext
    \completecontent
    \dorecurse{5}{\chapter{Chapter}
    \dorecurse{5}{\section{Section}}}
    \stoptext
```

En el primer par de corchetes está de lo que quieres que te genere marcadores. En el segundo es qué nivel quieres que te deje abierto.
