### ISSUE TITLE
Tamaño de papel

### ISSUE THREAD

**Issue by aradnix** [aradnix/consti#13]
Veo que el documento se ha formado en A4 cuando aquí usaríamos carta (letter) o bien oficio (legal) para documentos legales. No me parece que ayude en mucho el tamaño oficio si los títulos formados con \chapter abren siempre en página nueva y no en la misma en que termina el título anterior como se publican las constituciones por acá.

Me gusta como se ve con el título en la página siguiente, pero para que no haya blancos excesivamente grandes el tamaño carta me parece adecuado.

**Comment by ousia** [comment]
Por partes. El tamaño de hoja es:

``` tex
\setuppapersize[letter]
```

O, por supuesto, `legal`. Hay muchos más. Te recomiendo la [lista de órdenes en ConTeXt](http://www.pragma-ade.com/general/qrcs/setup-en.pdf), que te puede ayudar en esto.

Aunque siempre puedes definir tu propio tamaño de hoja. En ConTeXt, definir es crear:

``` tex
\definepapersize[miHoja][width=5cm,heigth=50cm]
\setuppapersize[miHoja]
```

Como ves, se puede configurar un tamaño nuevo de hoja definiéndolo antes.

Respecto a los títulos, como buena parte de ConTeXt: son configurables.

No hay nada que obligue a que los títulos de capítulo tengan que tener una página antes. La tienen por defecto y en muchos casos tienen mucho sentido. Pero es bueno borrarla cuando no se necesita.

Te hago una publicación con las dos cosas (611ec3f1dd14fa264ad25ca8e7823e2baec22289).

Las portadas, con más tiempo.

**Comment by ousia** [comment]
Cierro esta incidencia, porque creo que está resuelta.

#6 aborada precisamente la portada.

**Comment by aradnix** [comment]
Gracias, lo de los títulos ya vi como moverlo si en la configuración de  `\setuphead[chapter]` al elegir `page=no`. Lo del papel ya vi que se puede hacer fácilmente e incluso permite crear imposiciones fácilmente, algo que me parece muy útil para enviar cosas a imprenta.  Gracias por la lista de comandos, la imprimiré en la semana.

**Comment by ousia** [comment]
Por supuesto que tú decides.

Realmente no sé si la lista de órdenes es una cosa para imprimir o para tener en el ordenador.

Porque es importante poder buscar y no es algo que vayas a leer.

Pero tú mismo.

**Comment by aradnix** [comment]
Pues prefiero consultar en papel, sirve que la puedo revisar en el camino y aprenderme algunos cuando me desplazo por la ciudad. Solo tengo dudas respecto a git pero esas te las consultaré después por correo electrónico.
