### ISSUE TITLE
quizá te interese

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#14]
@aradnix, quizá te interese [_What is ConTeXt?_](http://www.pragma-ade.com/general/manuals/what-is-context.pdf) de Hans Hagen.

Disculpa si lo conoces.

**Comment by aradnix** [comment]
Hola, me parece que alguna vez vi esa portada, seguramente en el sitio de Pragma ADE pero no lo había leído, me parece muy claro y conciso, muchas gracias.
