### ISSUE TITLE
Líneas huérfanas y viudas

### ISSUE THREAD

**Issue by aradnix** [aradnix/consti#2]
Hay varias lineas huerfanas y viudas que corregir

**Comment by ousia** [comment]
Comento, aunque estén cerrados.

Viudas y huérfanas se evitan con:

``` tex
\startsetups[*lessstrict]
    \setup[reset]
    \widowpenalty=10000
    \clubpenalty=10000
    \brokenpenalty=0
\stopsetups
```

Es una configuración, que hay que añadirla a un elemento (por sí solo `\starsetups,,,, \stopsetups` no hace nada. Se añade a la configuración del documento:

``` tex
\setuplayout[setups=*lessstrict]
```

Hay alguna cosa más en mi publicación.

**Comment by aradnix** [comment]
¿Entonces eso como y donde debo implementarlo?

**Comment by ousia** [comment]
Siempre que sea una orden de configuración (`\setup...`), en el preámbulo.

El ejemplo mínimo sería:

``` tex
\setuppapersize[A6]
\startsetups[*lessstrict]
    \setup[reset]
    \widowpenalty=10000
    \clubpenalty=10000
    \brokenpenalty=0
\stopsetups
\setuplayout[setups=*lessstrict]
\starttext
\dorecurse{20}{\input knuth\par\input zapf\par}
\stoptext
```

Lo relevante es lo que está antes de `\starttext`. Añado un tamaño de hoja A6 (en la primera línea) para que se note más.

El texto en sí es irrelevante.
