### ISSUE TITLE
Formato de la tabla de contenidos

### ISSUE THREAD

**Issue by aradnix** [aradnix/consti#4]
Hay que darle formato a la tabla de contenidos. Tiene varios errores.

**Comment by ousia** [comment]
Creo que está solucionado con ebc49375e573424c5ceeb55b7de5753b2b87a337.

**Comment by ousia** [comment]
Perdón, si no fuese así. vuelve a abrir y dime qué fallla.

**Comment by ousia** [comment]
Estaba probando con la asignación de tareas.
