### ISSUE TITLE
Estructura

### ISSUE THREAD

**Issue by aradnix** [aradnix/consti#5]
Falta dar estructura al texto previo a los artículos y la información final tras el artículo transitorio.

**Comment by ousia** [comment]
¿Cómo habría de ser?

**Comment by aradnix** [comment]
Pues no sé, yo estaba pensando en unas tablas, pero aun no sale como quisiera. deja ver como hago el commit y lo agrego.

**Comment by ousia** [comment]
Para tablas te aconsejo que veas [_Extreme Tables_](http://www.pragma-ade.com/general/manuals/xtables-mkiv.pdf).

Será ignorancia, pero yo no me preocuparía de aprender otro modo de hacer tablas en ConTeXt.

**Comment by aradnix** [comment]
Pues no sé si sea ignorancia, en LaTeX las tablas son un dolor de cabeza... por no decir de otra región corporal. En ConTeXt es bastante más fácil ese asunto. Miraré lo que me sugieres.

**Comment by ousia** [comment]
Lo que leí no recuerdo dónde es que en TeX las tablas son ese tipo de elementos para los que no está muy pensado. Por eso es complicado hacerlas bien.

**Comment by aradnix** [comment]
No lo dudo y bueno no podía ser perfecto.

**Comment by ousia** [comment]
Más que perfecto, es que no existe la herramienta universal (o eso es el ordenador).

Si se especializa en construcción de párrafos disponiendo un texto, es fácil que lo que sea saltarse eso (tablas y objetos con colocación absoluta) salgan peor.

**Comment by aradnix** [comment]
Buen punto.

**Comment by ousia** [comment]
En la publicación de ahora, acabo de cambiarte la tabla.

Creo que se ve mejor, aunque está todavía en boceto.

Una cosa, yo no se usar otras tablas que `xtables`.

**Comment by aradnix** [comment]
Deja ver. Intento hacer 

> $ git pull

para cargar los cambios en mi disco duro y me aparece esto:

Updating b536ed8..6efdabd
error: Your local changes to the following files would be overwritten by merge:
    Consti.pdf
Please, commit your changes or stash them before you can merge.
Aborting

¿Debo usar otra cosa?

**Comment by ousia** [comment]
Si lo único que te cambia es `Consti.pdf`, haz lo siguiente:

```
git rm Consti.pdf Consti.tuc Consti.log
```

Así dejas de tener en `git` los archivos auxiliares.

Por si acaso, haz una copia de tu `Consti.tex` a otro directorio (aunque por lo que dices, no deberías necesitarla).

**Comment by aradnix** [comment]
Bien, ya hice eso, tuve que usar -f para forzar esto pero ya quedó. ¿Ahora debo hacer un fetch o simplemente con pull?

**Comment by ousia** [comment]
Hasta donde yo sé, `git pull` (nunca me he visto en usar `git fetch`).

**Comment by aradnix** [comment]
Creo que ya quedó resuelto este asunto, lo cierro.
