### ISSUE TITLE
Portada

### ISSUE THREAD

**Issue by aradnix** [aradnix/consti#6]
Hay que generar una portada.

**Comment by ousia** [comment]
¿Con la que hay serviría?

¿Cuál sería la necesidad entonces?

**Comment by aradnix** [comment]
Eso fue antes de inventarme una. No sé, me gusta mucho como la genera KOMA Script en LaTeX, en conTeXt siento que este rubro en particular es bastante pedestre, quizá estoy equivocado.

**Comment by ousia** [comment]
> Eso fue antes de inventarme una. No sé, me gusta mucho como la genera KOMA Script en LaTeX, en ConTeXt siento que este rubro en particular es bastante pedestre, quizá estoy equivocado.

Creo que asumes una perspectiva diferente. En ConTeXt no te lo dan hecho.

Pero si me das el ejemplo visual, yo intento hacer algo. Vuelvo a abrir la indicencia.

Una sugerencia. En GitHub se pueden añadir imágenes arrastrando y soltando. Archivos PDF no, pero hay un truco: cambia la extensión de `.pdf` a `.png` y te la sube.

Ahora que lo pienso, con una imagen `.png` también me vale.

**Comment by aradnix** [comment]
La preparo al rato y la subo, aunque por al diferencia de horarios seguramente la verás hasta mañana domingo.

**Comment by aradnix** [comment]
Me parece que el asunto de la portada era más bien una cuestión aparte, es decir no busco una portada tan grande (todavía), pero en vista de las posibilidades de ConTeXt bien se podría crear un modulo para ello. Por ahora creo que ha quedado bien el documento tal y como lo tengo (que no he actualizado al ultimo commit que hiciste y que al final opté por dejar sin la portada que hice y en tamaño oficio). Cierro esto de la portada porque creo que se puede resolver en una etapa futura.
