### ISSUE TITLE
erratas en el texto

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#7]
@aradnix, me temo que el texto tiene unas cuantas erratas.

> Union
> 
> comun

Son sólo dos ejemplos. No sé si el texto de [Wikisource](https://es.wikisource.org/wiki/Constitución_Mexicana_1857) estará mejor.

Aunque es sólo un comentario.

**Comment by aradnix** [comment]
Pues en general tiene muchos errores de acentuación. Ignoro si estaban así
en el documento original, tendría que ir al Archivo general y ver si me
dejan consultarlo, pero por ahora dejemos la parte ortográfica tal cual. De
hecho si ves dice setiembre en vez de septiembre y muchas preposiciones a
están acentuadas. Pensémoslo como un documento histórico escrito así en
1857.

**Comment by ousia** [comment]
Sí, por ejemplo _á_ se acentuaba (creo que por afrancesamiento).

No sé ortografía histórica, pero mucho me sorprendería que _unión_ o _común_ no se acentuasen.

De hecho (y creo que no lo he cambiado yo), _unión_ aparece una vez. En cambio _union_ aparece veintinueve veces.

**Comment by aradnix** [comment]
Pues incluso en los topónimos hay variaciones ortográficas todavía. Creo que eso era común en esa época. Prefiero dejarlo tal cual como muestra de la escritura en esos tiempos.
