### ISSUE TITLE
comillas

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#8]
No, las comillas no funcionan como en LaTeX.

En Linux, puedes introducirlas directamente (con AltGr y `z`/`x` [y `v`/`b`, para las comillas inglesas]).

Existe una orden `\quote`, que reconozco que no uso.

**Comment by aradnix** [comment]
Pues las puse como en LaTeX y no tuve problemas, pero las corregiré.​

**Comment by ousia** [comment]
Si te funcionaron, perfecto, pero a mí no me funcionaron en Fedora 20.

**Comment by aradnix** [comment]
Voy a revisar, no me gusta usar Fedora, me resulta muy inestable, odio SElinux y es lentísimo para actualizar. Y tienes razón, no quedan bien. Veo en conTeXt garden que \quotation{} lo hace, \quote{} es para comillas simples. Y con start-stop es para hacerlo en varios párrafos.

**Comment by ousia** [comment]
No te cambies a Fedora. Desde luego, no por esto.

En Ubuntu, eso debería funcionar también.

Perdón por las `\quote`. No lo he usado nunca.

**Comment by aradnix** [comment]
No me pienso cambiar, ya he usado Fedora y no es de mi agrado. Y deja ver si compila bien con eso que usé.

**Comment by aradnix** [comment]
Pues... no queda bien, estoy usando lo que ponen aquí: http://wiki.contextgarden.net/Quotes supongo que me falta definir en el preámbulo las comillas, creo que no funcionan automáticamente. Al menos no con Mk IV.

**Comment by ousia** [comment]
Aquí hay dos cuestiones:
1. La tipográfica. Creo que es mejor usar comillas latinas, porque las inglesas son mejores donde no hay marcas diacríticas.
2. La de escritura. Seré muy complejo, pero las comillas prefiero escribirlas yo, que no me las sustituyan.

A mí esto me funciona (adaptado de [ConTeXt Garden](http://wiki.contextgarden.net/Quotes):

``` tex
\setuplanguage[es]
[leftquotation=«,
 rightquotation=»,
 leftquote=‹,
 rightquote=›]

\mainlanguage[es]

\starttext
Following example is not correct. Typography rules for Czech language
for quotes \quotation{of text in quotes define \quotation{nested inner} quotes}.

And now correct version. Typography rules for Czech language for quotes
\quotation{of text in quotes define to \quote{nested inner} quotes}.

\setupdelimitedtext[quotation:1][left={\symbol[leftquotation]},right={\symbol[rightquotation]}]
\setupdelimitedtext[quotation:2][left={\symbol[leftquote]}, right={\symbol[rightquote]}]

Automatic nesting. Typography rules for Czech language for quotes \quotation{of
text in quotes define to \quotation{nested inner} quotes}.
\stoptext
```

**Comment by aradnix** [comment]
Pues sinceramente yo soy más de la idea de usar otro tipo de distinciones tipográficas. Las comillas y el subrayado son buenas opciones en una máquina de escribir, cuando se trabaja con tipos hay más opciones. Pero quería ser fiel al texto y por eso usar las comillas. Y acá es más común emplear las comillas altas o inglesas en vez de las que llamas latinas que también son nombradas francesas o españolas. Solo tengo tres incidencias de comillas, ¿cómo sugieres agregarlas manualmente, con algún par de caracteres de unicode acaso?

**Comment by ousia** [comment]
Creo que el subrayado y las comillas vienen de lugares distintos.

El subrayado tiene sentido en manuscrito y mecanografiado. La cursiva es la opción propia de la imprenta.

Las comillas son una opción tipográfica genuina. Si bien se usan menos que cuando no tienes otras opciones.

Para citar un texto, como:

> Platón dijo: «que nadie entre sin saber geometría» —«ἀγεωμέτρητος μηδεὶς εἰσίτω»—.

Usar cursiva en las citas anteriores es innecesario. Y hacer un párrafo de cita, no procede porque es muy corta la cita.

Aquí la mayoría de la gente usa comillas inglesas, pero por desconocimiento. Las latinas o francesas —siento repetirme— tienen sentido cuando tienes tildes. En francés, tienen tres acentos, con lo que las comillas altas es fácil que molesten.

¿Cómo hacerlo en Linux? `AltGr+z` y `AltGr+x` (con `AltGr+v` y `AltGr+b` consigues comillas inglesas).

**Comment by aradnix** [comment]
Pues la tradición tipográfica en México, quizá por ignorancia o por influencia del vecino del Norte opta casi siempre por las comillas inglesas. Yo procuro usar en general las comillas lo menos posible, no porque no sea una opción tipográfica genuina y a la altura, sino porque como dije junto al subrayado eran las dos opciones mecanográficas de énfasis y aun hoy siguen siendo preferibles para muchos. Probaré lo de las comillas, gracias.

**Comment by ousia** [comment]
No sé, aquí lo de la tradición tipográfica es algo que consigues en ConTeXt con el siguiente archivo:

``` tex
\starttext
    \startTEXpage[offset=2em]
        \input zapf
    \stopTEXpage
\stoptext
```

Muchas presuntas tradiciones tipográficas son prácticas más o menos empobrecias desde la introducción de los ordenadores para la composición de libros.

No sólo son las comillas. Es el uso mucho más generalizado de la negrita. Es no sangrar después de títulos o espacios verticales mayores.... y así hasta el infinito.

Y a lo mejor porque no había otra opción en en programa de turno o porque sencillamente era la opción por defecto.

MIentras tanto, editoriales de reconocido prestigio (no diré nombres, porque esto es público) no son capaces de ligar los pares _fi_ o _fl_. Es tipografía digital, no un programa concreto (sea TeX o _Adobe InDesign_).

Cierro porque entiendo que está resuelto.

**Comment by aradnix** [comment]
Pues por lo que he aprendido de tipografía y libros y diseño en los últimos 8 años o tal vez más, muchos de estos vicios se remontan a los días en que la máquina de escribir era la tecnología de punta. Uno de esos era el no acentuar las mayúsculas o letras de caja alta. Esto debido a que las tildes, cuando fueron incorporadas en las máquinas de escribir se solapaban con dichas letras. Pero si no mal recuerdo la RAE en 1990 cambió de parecer pues ya no había justificación técnica para ello con el uso de las computadoras u ordenadores.

Las negritas comenzaron su azote en el siglo XIX en detrimento de versalitas, versalitas cursivas y de las propias cursivas, y recuperarlas ha sido algo relativamente reciente. En matemáticas por ejemplo, se usa y abusa de las negritas para representar vectores (en minúscula) y matrices y tensores (mayúsculas). De modo que libros desde álgebra lineal, análisis vectorial o mecánica están plagados de negritas por todos lados. Yo prefiero usar una convención diferente aprovechando lo que me da LaTeX para evitar esos excesos.

Lo que me llamó la atención además en este comentario es lo que comentas de sangrar párrafos después de las cabeceras. Yo lo considero un error ortotipográfico y una redundancia, pues la sangría se usa, entre otros métodos para indicar una separación de párrafos. Pero una cabecera es un indicador visual suficientemente claro para evitar sangrar el párrafo subsecuente. Yo por eso lo evito, de igual modo si hay alguna figura o un espacio suficientemente grande que evite confusión. Todo esto claro usando la forma tradicional de componer párrafos: sin espacio entre ellos y una sangría que sea de aproximadamente un cuadratín al inicio de cada párrafo.

Con el párrafo moderno (según Tschichold)  la sangría es innecesaria al haber una linea en blanco que distingue bien ambos párrafos. Ahora que lo pienso, no sé que sugiera el manual de diseño editorial de Jorge de Buen, tendré que consultarlo.

**Comment by ousia** [comment]
En cuanto a la acentuación de mayúsculas creo que era expresamente por las máquinas de escribir. No era incorrecto acentuar (hasta donde recuerdo) las mayúsculas. Es que hacerlo en una máquina de escribir trastocaba un escrito (no podía hacerse en la misma línea).

En la imprenta, no había especiales problemas (al azar, [un ejemplo](https://archive.org/stream/galds00antn#page/2/mode/2up), [otro](https://archive.org/stream/rubndaro00lugo#page/n3/mode/2up) y [otro más](https://archive.org/stream/lavidaderubnda00daruoft#page/n7/mode/2up)).

Lo de sangrar los párrafos en español es una constante. En principio, deben sangrarse todos. Por lo menos, esa ha sido la práctica en España. Probablemente, por influencia francesa. Creo que es extraordinariamente práctico, porque en el propio párrafo se marca la primera línea (sin necesidad de ver qué viene antes). Es hacer más visible la primera línea, no sólo por la separación anterior.

No me cabe duda de que en Alemania la regla de Tschichold sea lógica y la sigan. Pero es distinto, es como ellos escriben las comillas al revés (`»«` y `„“`).

De hecho, la separación entre párrafos creo que no anula el sangrado del párrafo siguiente ni en países de habla inglesa. Hasta donde yo recuerdo, creo que es una práctica actual.

Además, el problema de no sangrar la primera línea del primer párrafo es que se marca visualmente del resto. Y no creo que eso sea lo que se persiga.

Creo que más que la separación entre párrafos, lo que la sangría indica es el comienzo del párrafo. No son necesariamente lo mismo, aunque estén totalmente vinculados.

**Comment by aradnix** [comment]
Pues justo eso que explicas de la máquina de escribir y los acentos es lo que dije antes. Respecto a la sangría, Yo la acostumbro solamente cuando compongo textos en párrafo "clásico" sin espacio entre ellos, donde la sangría es necesaria. Procuro no ponerla cuando el párrafo es inicial porque me parece redundante. Sin embargo acabo de revisar someramente algunos libros que tengo e incluso en libros rusos veo que es común poner sangría en párrafo inicial. Pero también es cierto que los he visto quienes lo omiten. Una forma de hacerlo es usando letras capitales grandes. Pero creo que también depende de mucho de la página, si el interlineado es modesto creo que es bueno colocarla, si el tipo seleccionado tiene buena altura x y el interlineado es más generoso podría tal vez prescindir de ella. 

Lo que comentaba de Jan Tschichold no se quedó solamente en Alemania, lo he visto e muchos diseños en diferentes lenguas incluido el español.  En cuanto a las comillas, pues desde Alemania hasta donde deja de escribirse en latino y se hace en cirilico las comillas se usan "al revés". Pero eso nada tien que ver, es diferente.

**Comment by ousia** [comment]
> Pues justo eso que explicas de la máquina de escribir y los acentos es lo que dije antes.

Perdona, te entendí mal.

Respecto a la sangría, podríamos hablar mucho de eso. Reconozco que es razonar lo que en el fondo son preferencias (si bien están respaldadas por prácticas habituales).

Por supuesto que no hay que sangrar todos los párrafos, como los que tienen letras dibujadas (o los que empiezan antes de la primera letra, como las listas o las notas al pie).

Lo que creo que no sangrando ciertos párrafos hay una incoherencia visual a nivel de párrafo. Y desde luego, en España, si no se sangran no es por otra cosa que por influencia extranjera. Nuestra práctica no ha sido esa.

Sé que el uso de las comilas es otra cuestión. Era sólo un ejemplo. Por lo que sé, las comillas las usan al revés, pero no todos igual. En danés es distinto que en alemán (la comilla de cierre es la nuestra [u otra, ya no recuerdo]). Y en checo creo que también es distinto al alemán.

**Comment by aradnix** [comment]
Hace rato estuve revisando libros que tengo y encontré muchos donde se sangran todos los párrafos a rajatabla, incluso algunos rusos que tengo. Hace rato salí y pasé a una librería del FCE (Fondo de Cultura Económica), miré varios libros y me acordé de esto de la sangría y noto como muchos libros editados aquí por el FCE siguen el criterio que te dije, otros libros que venden de otras latitudes de la Hispanidad difieren.

En cuanto a las comillas, el danés es más cercano al sueco y noruego incluso en como escriben que al alemán, no me sorprende que su uso de las comillas difiera. El checo se alejó un tanto de la norma alemana a partir de la reforma husita del siglo XV, pero el polaco no y las comillas a la usanza alemana se acostumbran hasta en Rusia, no dudo que en Ucrania y demás países sea parecido, pero no puedo confirmarlo.
