### ISSUE TITLE
sangrado de listas

### ISSUE THREAD

**Issue by ousia** [aradnix/consti#9]
Como puedes ver en la publicación 779705386fb3f721abcec4ad33dc1fd266e661f2, he sangrado las enumeraciones en números romanos.

Se puede hacer individual o globlamente. Como todas son iguales, lo he hecho global con:

``` tex
\setupitemize[margin=yes]
```

Creo que en este caso es importante hacerlo, para mostrar que la lista está dentro del artículo. Es una cuestión visual.

**Comment by aradnix** [comment]
Perfecto, con eso ya queda resuelto el problema de viudas y huérfanas. Sin embargo me temo que con las enumeraciones en romanos no puedo cantar victoria. He probado con

> \setupitemize[margin=yes]

pero no mejora mucho el asunto, he intentado:

> \setupitemize[margin=yes,4*broad]

pero sigue igual, dentro de mi lógica y desconocimiento aun de conTeXt he querido usar algo más grande como:

> \setupitemize[margin=yes,8*broad]

Pero se ve igual. No sé como resolverlo. Tengo números romanos muy grandes o anchos mas bien como XXVIII.

**Comment by ousia** [comment]
La posibilidad lógica es hacer que el número esté alineado a la derecha.

Y el margen tiene que tener más ancho que el normal.

Está en 492781426b69e8da5c09c9e7b1955015588769d7.

**Comment by ousia** [comment]
Perdón, explico lo de la _posibilidad lógica_.

Si el ancho es tan variable, o tienes un _I_ con muchísimo espacio o no tendrás un _XXVIII_ con espacio.

Sólo eso :smiley:.
